### ISSUE TITLE
PHP代码实现跳跃表bug

### ISSUE THREAD

**Issue by SkyeInfo** [2lovecode/code-segment#2]
PATH: code-segment/PhpCodes/DataStructureAndAlgorithm/SkipList/SkipList.php

> Bug: 

randomLevel()方法返回随机level时，在当前上下文环境（max_level = 3）中level层级最高到1（起始为0）导致第2层级根本不会有链表出现

> 修复建议：

```
private function randomLevel() {
     $level = 1;
 
     for ($i = 1; $i < $this->maxLevel; $i++) {
         $r = rand();
         if ($r % 2 == 1) {
             $level++;
         }
     }
 
     return $level;
}
```

> 我的联系方式: 

skyeinfo@qq.com

**Comment by 2lovecode** [comment]
感谢您指出的错误。
这是一个严重的错误：在随机生成跳跃表层级时，缺少了多次随机过程，造成跳跃表层级无法增长，无法达到降低查询次数的目的。
此问题已经根据您的建议修复。再次感谢。
