### ISSUE TITLE
PHP读取超大文件问题

### ISSUE THREAD

**Issue by kajweb** [2lovecode/code-segment#4]
https://github.com/2lovecode/code-segment/blob/master/PhpCodes/PhpSyntaxTestCode/GetFileLastNumRow.php

当文件行数小于设置的行数，是否会触发异常？

**Comment by 2lovecode** [comment]
确实会有问题，已解决
在移动文件游标之前，判断若到达文件开头则跳出读取逻辑

`
if (ftell($handle) == 1) {
     break;
}
`
